// LOCALHOST
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/63336cebc129cb890c61d5e1
### 
GET http://localhost:8080/contacts/63336cebc129cb890c61d5e2 
### 
GET http://localhost:8080/contacts/63336cebc129cb890c61d5e3

// PRODUCTION Deploy 
### 
GET https://backend-341.onrender.com/contacts 
### 
GET https://backend-341.onrender.com/contacts/63336cebc129cb890c61d5e1 
### 
GET https://backend-341.onrender.com/contacts/63336cebc129cb890c61d5e2 
### 
GET https://backend-341.onrender.com/contacts/63336cebc129cb890c61d5e3
